project:
  type: website
  output-dir: docs

website:
  title: "TEI Introduction"
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Outline
  sidebar: 
      style: docked
      contents:
        - href: materials/slides/introduction.qmd
          text: "Introduction"
        - href: materials/activity/01-activity1/creating_tei_files.qmd
          text: "Creating TEI files"
format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

