project:
  type: website
  output-dir: docs

website:
  title: "TEI Introduction"
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Outline
      - href: materials/activity/01-activity1/creating_tei_files.qmd
        text: "Activity 1"
      - href: materials/activity/02-activity2/dates_places_editorial.qmd
        text: "Activity 2"
      - href: materials/activity/00-reading-documentation/reading_documentation.qmd
        text: "Documentation"
format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

